<!doctype html>
<html lang="ps" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>سیدولي افغاني نړیواله ټولنیزه شبکه</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Tahoma,Arial,sans-serif;background:#f0f2f5;color:#1c1e21}button,input,textarea,select{font:inherit}button{cursor:pointer;border:0;border-radius:8px;padding:10px 14px;background:#1877f2;color:#fff}.danger{background:#e41e3f}.muted{color:#65676b}.hidden{display:none!important}.app{max-width:1100px;margin:auto}.top{position:sticky;top:0;z-index:5;background:#fff;border-bottom:1px solid #ddd;padding:10px}.brand{font-size:22px;font-weight:bold;color:#1877f2}.nav{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.nav button{background:#e4e6eb;color:#111}.nav button.active{background:#1877f2;color:#fff}.grid{display:grid;grid-template-columns:260px 1fr;gap:16px;margin:16px}.card{background:#fff;border-radius:12px;padding:16px;margin-bottom:14px;box-shadow:0 1px 3px #0002}.avatar{width:48px;height:48px;border-radius:50%;object-fit:cover;background:#ddd}.row{display:flex;align-items:center;gap:10px}.grow{flex:1}.feed textarea{width:100%;min-height:80px;border:1px solid #ddd;border-radius:10px;padding:10px;resize:vertical}.post{padding-top:12px;border-top:1px solid #eee;margin-top:12px}.post img,.media{max-width:100%;border-radius:10px;margin-top:10px}.actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.actions button{background:#e4e6eb;color:#111}.actions button.on{background:#1877f2;color:#fff}.story{display:inline-flex;flex-direction:column;align-items:center;width:90px}.story img{width:65px;height:65px;border-radius:50%;object-fit:cover;border:3px solid #1877f2}.stories{display:flex;overflow:auto;gap:10px}.login{max-width:420px;margin:8vh auto}.form{display:grid;gap:10px}.form input,.form textarea,.form select{width:100%;padding:11px;border:1px solid #ccd0d5;border-radius:8px}.toast{position:fixed;bottom:20px;left:20px;background:#222;color:#fff;padding:12px 18px;border-radius:8px;z-index:20}.modal{position:fixed;inset:0;background:#0008;display:flex;align-items:center;justify-content:center;z-index:10}.modal>.card{width:min(600px,92vw);max-height:90vh;overflow:auto}.list{display:grid;gap:8px}.item{padding:10px;background:#f5f6f7;border-radius:8px}.side button{width:100%;margin-bottom:7px;background:#fff;color:#111;text-align:right}.status{font-size:12px}.online{color:#16a34a}.offline{color:#777}@media(max-width:750px){.grid{grid-template-columns:1fr;margin:8px}.side{display:none}.top{padding:8px}.brand{font-size:18px}}
</style>
</head>
<body>
<div id="root"></div><div id="toast" class="toast hidden"></div>
<script>
/* ================= API CONFIG ================= */
const API_BASE = localStorage.getItem('saidwali_api') || 'https://saidwali-social-api.walizaad2.workers.dev';
let token=localStorage.getItem('saidwali_token')||'';
let me=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(x){$('#toast').textContent=x;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),3000)}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(API_BASE+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok){if(r.status===401){token='';localStorage.removeItem('saidwali_token');render()}throw Error(d.error||'API error')}return d}
async function post(path,data){return api(path,{method:'POST',body:JSON.stringify(data)})}
async function put(path,data){return api(path,{method:'PUT',body:JSON.stringify(data)})}
async function del(path,data){return api(path,{method:'DELETE',body:JSON.stringify(data)})}

/* ================= AUTH ================= */
function render(){document.body.innerHTML=token?appHTML():authHTML();if(token)loadMe();}
function authHTML(){return `<div class="login card"><h1 class="brand">سیدولي افغاني نړیواله ټولنیزه شبکه</h1><div id="authBox">${loginForm()}</div></div>`}
function loginForm(){return `<h2>ننوتل</h2><form class="form" onsubmit="login(event)"><input id="identifier" placeholder="Username / Email / Phone" required><input id="password" type="password" placeholder="Password" required><button>ننوتل</button></form><p>حساب نه لرئ؟ <button onclick="$('#authBox').innerHTML=registerForm()">ثبت نام</button></p>`}
function registerForm(){return `<h2>نوی حساب</h2><form class="form" onsubmit="register(event)"><input id="full_name" placeholder="بشپړ نوم"><input id="username" placeholder="Username" required><input id="email" type="email" placeholder="Email"><input id="phone" placeholder="Phone"><input id="password" type="password" placeholder="Password (8+)" required><button>حساب جوړول</button></form><p><button onclick="$('#authBox').innerHTML=loginForm()">بېرته ننوتل</button></p>`}
async function login(e){e.preventDefault();try{const d=await post('/api/auth/login',{identifier:$('#identifier').value,password:$('#password').value});token=d.token;localStorage.setItem('saidwali_token',token);render()}catch(x){toast(x.message)}}
async function register(e){e.preventDefault();try{const d=await post('/api/auth/register',{full_name:$('#full_name').value,username:$('#username').value,email:$('#email').value||null,phone:$('#phone').value||null,password:$('#password').value});token=d.token;localStorage.setItem('saidwali_token',token);render()}catch(x){toast(x.message)}}
async function logout(){try{await post('/api/auth/logout',{})}catch{}token='';localStorage.removeItem('saidwali_token');render()}

/* ================= APP ================= */
function appHTML(){return `<header class="top"><div class="app"><span class="brand">سیدولي شبکه</span><div class="nav"><button onclick="show('home')">کور</button><button onclick="show('profile')">پروفایل</button><button onclick="show('friends')">ملګري</button><button onclick="show('messages')">پیغامونه</button><button onclick="show('notifications')">خبرتیاوې</button><button onclick="show('search')">لټون</button><button onclick="show('pages')">پاڼې</button><button onclick="show('groups')">ګروپونه</button><button onclick="show('events')">پېښې</button><button onclick="show('marketplace')">بازار</button><button onclick="show('settings')">تنظیمات</button><button onclick="logout()" class="danger">وتل</button></div></div></header><main id="view" class="app"></main>`}
async function loadMe(){try{const d=await api('/api/me');me=d.user;show('home')}catch(x){toast(x.message)}}
async function show(page){const v=$('#view');v.innerHTML='<div class="card">Loading...</div>';try{if(page==='home')await home(v);else if(page==='profile')await profile(v,me.id);else if(page==='friends')await friends(v);else if(page==='messages')await messages(v);else if(page==='notifications')await notifications(v);else if(page==='search')searchView(v);else if(page==='pages')await pages(v);else if(page==='groups')await groups(v);else if(page==='events')await events(v);else if(page==='marketplace')await marketplace(v);else if(page==='settings')await settings(v)}catch(x){v.innerHTML=`<div class="card">${esc(x.message)}</div>`}}

/* ================= HOME / STORIES / POSTS ================= */
async function home(v){const [s,p]=await Promise.all([api('/api/stories'),api('/api/posts')]);v.innerHTML=`<div class="grid"><aside class="side"><div class="card"><b>${esc(me.full_name||me.username)}</b><p class="muted">@${esc(me.username)}</p><button onclick="show('profile')">زما پروفایل</button><button onclick="show('friends')">ملګري</button><button onclick="show('messages')">پیغامونه</button></div></aside><section class="feed"><div class="card"><h3>Stories</h3><div class="stories">${(s.stories||[]).map(x=>`<div class="story"><img src="${esc(x.media_url||x.profile_photo||'')}" onerror="this.style.visibility='hidden'"><small>${esc(x.username||x.full_name||'کارن')}</small></div>`).join('')}</div><hr><form onsubmit="createStory(event)" class="form"><select id="story_type"><option value="text">متن</option><option value="image">عکس</option><option value="video">ویډیو</option></select><input id="story_media" placeholder="Media URL"><input id="story_content" placeholder="Story متن"><button>Story جوړول</button></form></div><div class="card"><h3>نوی پوسټ</h3><form onsubmit="createPost(event)" class="form"><textarea id="post_content" placeholder="څه فکر کوئ؟"></textarea><select id="post_privacy"><option>public</option><option>friends</option><option>private</option></select><input id="post_location" placeholder="Location"><input id="post_feeling" placeholder="Feeling"><input id="post_media" placeholder="Media URL (اختیاري)"><button>پوسټ خپرول</button></form></div><div id="posts">${(p.posts||[]).map(postHTML).join('')}</div></section></div>`}
function postHTML(p){return `<article class="card post" id="post-${p.id}"><div class="row"><img class="avatar" src="${esc(p.profile_photo||'')}" onerror="this.style.visibility='hidden'"><div><b>${esc(p.full_name||p.username)}</b><div class="muted">@${esc(p.username)} · ${esc(p.created_at)}</div></div></div><p>${esc(p.content)}</p>${p.media_url?`<img class="media" src="${esc(p.media_url)}">`:''}<div class="muted">❤️ ${p.reactions_count||0} · 💬 ${p.comments_count||0} · ↗ ${p.shares_count||0}</div><div class="actions"><button class="${p.reacted?'on':''}" onclick="react(${p.id},'like')">❤️ Like</button><button onclick="comment(${p.id})">💬 Comment</button><button onclick="save(${p.id})">🔖 Save</button>${Number(p.user_id)===Number(me.id)?`<button class="danger" onclick="deletePost(${p.id})">Delete</button>`:''}</div></article>`}
async function createPost(e){e.preventDefault();try{const media=$('#post_media').value.trim();await post('/api/posts',{content:$('#post_content').value,privacy:$('#post_privacy').value,location:$('#post_location').value,feeling:$('#post_feeling').value,media:media?[{media_type:'image',media_url:media}]:[]});toast('پوسټ جوړ شو');show('home')}catch(x){toast(x.message)}}
async function deletePost(id){if(!confirm('پوسټ حذف شي؟'))return;try{await del('/api/posts/'+id);show('home')}catch(x){toast(x.message)}}
async function react(id,type){try{await post('/api/reactions',{post_id:id,reaction_type:type});show('home')}catch(x){toast(x.message)}}
async function comment(id){const c=prompt('تبصره ولیکئ');if(!c)return;try{await post('/api/comments',{post_id:id,content:c});show('home')}catch(x){toast(x.message)}}
async function save(id){try{await post('/api/saved-posts',{post_id:id});toast('Save شو')}catch(x){toast(x.message)}}
async function createStory(e){e.preventDefault();try{await post('/api/stories',{story_type:$('#story_type').value,media_url:$('#story_media').value,content:$('#story_content').value,privacy:'friends',expires_at:new Date(Date.now()+86400000).toISOString()});toast('Story جوړ شو');show('home')}catch(x){toast(x.message)}}

/* ================= PROFILE ================= */
async function profile(v,id){const d=await api('/api/profile?user_id='+id);const p=d.profile;v.innerHTML=`<div class="card"><div style="height:180px;background:#ddd url('${esc(p.cover_photo||'')}') center/cover;border-radius:10px"></div><div class="row" style="margin-top:-30px;padding:10px"><img class="avatar" style="width:80px;height:80px;border:4px solid white" src="${esc(p.profile_photo||'')}" onerror="this.style.visibility='hidden'"><div><h2>${esc(p.full_name)}</h2><div>@${esc(p.username)} ${p.is_verified?'✓':''}</div></div></div></div><div class="card"><h3>پروفایل سمول</h3><form class="form" onsubmit="updateProfile(event)"><input id="pf_full_name" value="${esc(p.full_name)}" placeholder="Full name"><textarea id="pf_bio">${esc(p.bio)}</textarea><input id="pf_profile_photo" value="${esc(p.profile_photo)}" placeholder="Profile photo URL"><input id="pf_cover_photo" value="${esc(p.cover_photo)}" placeholder="Cover photo URL"><input id="pf_location" value="${esc(p.location)}" placeholder="Location"><input id="pf_website" value="${esc(p.website)}" placeholder="Website"><input id="pf_work" value="${esc(p.work)}" placeholder="Work"><input id="pf_education" value="${esc(p.education)}" placeholder="Education"><input id="pf_birthday" value="${esc(p.birthday)}" placeholder="Birthday"><input id="pf_gender" value="${esc(p.gender)}" placeholder="Gender"><button>ذخیره</button></form></div>`}
async function updateProfile(e){e.preventDefault();try{await put('/api/profile',{full_name:$('#pf_full_name').value,bio:$('#pf_bio').value,profile_photo:$('#pf_profile_photo').value,cover_photo:$('#pf_cover_photo').value,location:$('#pf_location').value,website:$('#pf_website').value,work:$('#pf_work').value,education:$('#pf_education').value,birthday:$('#pf_birthday').value,gender:$('#pf_gender').value});toast('پروفایل تازه شو');show('profile')}catch(x){toast(x.message)}}

/* ================= FRIENDS / FOLLOW ================= */
async function friends(v){const d=await api('/api/friends');const r=await api('/api/friend-requests');v.innerHTML=`<div class="card"><h2>ملګري</h2><div class="list">${(d.friends||[]).map(x=>`<div class="item row"><span class="grow"><b>${esc(x.full_name||x.username)}</b> @${esc(x.username)}</span></div>`).join('')||'<span>ملګري نشته</span>'}</div></div><div class="card"><h2>Friend Requests</h2><div class="list">${(r.requests||r.received||[]).map(x=>`<div class="item row"><span class="grow">${esc(x.full_name||x.username||x.sender_username)}</span><button onclick="respond(${x.id},'accepted')">قبول</button><button class="danger" onclick="respond(${x.id},'rejected')">رد</button></div>`).join('')||'<span>درخواست نشته</span>'}</div><hr><form class="form" onsubmit="sendFriend(event)"><input id="friend_id" type="number" placeholder="د کارن ID"><button>Friend Request واستوئه</button></form></div>`}
async function sendFriend(e){e.preventDefault();try{await post('/api/friend-requests',{receiver_id:Number($('#friend_id').value)});toast('درخواست واستول شو')}catch(x){toast(x.message)}}
async function respond(id,status){try{await post('/api/friend-requests/respond',{request_id:id,status});show('friends')}catch(x){toast(x.message)}}

/* ================= MESSAGES ================= */
async function messages(v){const d=await api('/api/conversations');v.innerHTML=`<div class="card"><h2>پیغامونه</h2><div class="list">${(d.conversations||[]).map(c=>`<div class="item" onclick="openConversation(${c.id})"><b>${esc(c.title||'Conversation #'+c.id)}</b><div class="muted">${esc(c.updated_at||'')}</div></div>`).join('')||'Conversation نشته'}</div><hr><form class="form" onsubmit="newConversation(event)"><input id="conv_title" placeholder="Conversation title"><input id="conv_user" type="number" placeholder="د بل کارن ID"><button>Conversation جوړول</button></form></div><div id="chat"></div>`}
async function newConversation(e){e.preventDefault();try{await post('/api/conversations',{title:$('#conv_title').value,user_id:Number($('#conv_user').value)});show('messages')}catch(x){toast(x.message)}}
async function openConversation(id){const d=await api('/api/messages?conversation_id='+id);$('#chat').innerHTML=`<div class="card"><h3>Chat #${id}</h3><div class="list">${(d.messages||[]).map(m=>`<div class="item"><b>${esc(m.sender_id==me.id?'زه':'کارن')}</b>: ${esc(m.content)}</div>`).join('')}</div><form class="form" onsubmit="sendMsg(event,${id})"><input id="msg" placeholder="پیغام"><button>استول</button></form></div>`}
async function sendMsg(e,id){e.preventDefault();try{await post('/api/messages',{conversation_id:id,content:$('#msg').value,message_type:'text'});openConversation(id)}catch(x){toast(x.message)}}

/* ================= NOTIFICATIONS ================= */
async function notifications(v){const d=await api('/api/notifications');v.innerHTML=`<div class="card"><h2>خبرتیاوې</h2><button onclick="readNotifications()">ټولې لوستل شوې</button><div class="list" style="margin-top:10px">${(d.notifications||[]).map(n=>`<div class="item"><b>${esc(n.title||n.type)}</b><div>${esc(n.message)}</div><small>${esc(n.created_at)}</small></div>`).join('')||'خبرتیا نشته'}</div></div>`}
async function readNotifications(){try{await post('/api/notifications/read',{});show('notifications')}catch(x){toast(x.message)}}

/* ================= SEARCH ================= */
function searchView(v){v.innerHTML=`<div class="card"><h2>لټون</h2><form class="form" onsubmit="doSearch(event)"><input id="q" placeholder="Users, posts, groups, pages..."><select id="search_type"><option value="all">all</option><option value="users">users</option><option value="posts">posts</option><option value="groups">groups</option><option value="pages">pages</option><option value="hashtags">hashtags</option></select><button>لټون</button></form></div><div id="results"></div>`}
async function doSearch(e){e.preventDefault();try{const d=await api('/api/search?q='+encodeURIComponent($('#q').value)+'&type='+encodeURIComponent($('#search_type').value));$('#results').innerHTML='<div class="card"><pre style="white-space:pre-wrap">'+esc(JSON.stringify(d,null,2))+'</pre></div>'}catch(x){toast(x.message)}}

/* ================= PAGES / GROUPS / EVENTS / MARKETPLACE ================= */
async function pages(v){const d=await api('/api/pages');v.innerHTML=`<div class="card"><h2>پاڼې</h2><div class="list">${(d.pages||[]).map(x=>`<div class="item"><b>${esc(x.name)}</b> @${esc(x.username)}<div>${esc(x.description)}</div></div>`).join('')||'پاڼه نشته'}</div><hr><form class="form" onsubmit="createPage(event)"><input id="page_name" placeholder="Name" required><input id="page_username" placeholder="Username" required><textarea id="page_description" placeholder="Description"></textarea><input id="page_category" placeholder="Category"><button>پاڼه جوړول</button></form></div>`}
async function createPage(e){e.preventDefault();try{await post('/api/pages',{name:$('#page_name').value,username:$('#page_username').value,description:$('#page_description').value,category:$('#page_category').value});show('pages')}catch(x){toast(x.message)}}
async function groups(v){const d=await api('/api/groups');v.innerHTML=`<div class="card"><h2>ګروپونه</h2><div class="list">${(d.groups||[]).map(x=>`<div class="item"><b>${esc(x.name)}</b><div>${esc(x.description)}</div></div>`).join('')||'ګروپ نشته'}</div><hr><form class="form" onsubmit="createGroup(event)"><input id="group_name" placeholder="Name" required><textarea id="group_description" placeholder="Description"></textarea><select id="group_privacy"><option>public</option><option>private</option></select><input id="group_category" placeholder="Category"><button>ګروپ جوړول</button></form></div>`}
async function createGroup(e){e.preventDefault();try{await post('/api/groups',{name:$('#group_name').value,description:$('#group_description').value,privacy:$('#group_privacy').value,category:$('#group_category').value});show('groups')}catch(x){toast(x.message)}}
async function events(v){const d=await api('/api/events');v.innerHTML=`<div class="card"><h2>پېښې</h2><div class="list">${(d.events||[]).map(x=>`<div class="item"><b>${esc(x.title)}</b><div>${esc(x.location)} · ${esc(x.start_at)}</div><p>${esc(x.description)}</p></div>`).join('')||'پېښه نشته'}</div><hr><form class="form" onsubmit="createEvent(event)"><input id="event_title" placeholder="Title" required><textarea id="event_description" placeholder="Description"></textarea><input id="event_location" placeholder="Location"><input id="event_start" type="datetime-local" required><input id="event_end" type="datetime-local"><select id="event_privacy"><option>public</option><option>private</option></select><button>پېښه جوړول</button></form></div>`}
async function createEvent(e){e.preventDefault();try{await post('/api/events',{title:$('#event_title').value,description:$('#event_description').value,location:$('#event_location').value,start_at:new Date($('#event_start').value).toISOString(),end_at:$('#event_end').value?new Date($('#event_end').value).toISOString():null,privacy:$('#event_privacy').value});show('events')}catch(x){toast(x.message)}}
async function marketplace(v){const d=await api('/api/marketplace');v.innerHTML=`<div class="card"><h2>Marketplace</h2><div class="list">${(d.products||d.items||[]).map(x=>`<div class="item"><b>${esc(x.title)}</b> — ${esc(x.price)} ${esc(x.currency||'AFN')}<p>${esc(x.description)}</p><small>${esc(x.location)}</small></div>`).join('')||'اعلان نشته'}</div><hr><form class="form" onsubmit="createMarket(event)"><input id="mp_title" placeholder="Title" required><textarea id="mp_description" placeholder="Description"></textarea><input id="mp_price" type="number" step="0.01" placeholder="Price" required><input id="mp_currency" value="AFN"><input id="mp_location" placeholder="Location"><button>اعلان جوړول</button></form></div>`}
async function createMarket(e){e.preventDefault();try{await post('/api/marketplace',{title:$('#mp_title').value,description:$('#mp_description').value,price:Number($('#mp_price').value),currency:$('#mp_currency').value,location:$('#mp_location').value});show('marketplace')}catch(x){toast(x.message)}}

/* ================= SETTINGS ================= */
async function settings(v){const d=await api('/api/settings');const s=d.settings||{};v.innerHTML=`<div class="card"><h2>تنظیمات</h2><form class="form" onsubmit="updateSettings(event)"><select id="set_language"><option value="ps">Pashto</option><option value="fa">Dari</option><option value="en">English</option></select><select id="set_theme"><option>light</option><option>dark</option></select><label><input id="set_notifications" type="checkbox" ${s.notifications_enabled?'checked':''}> Notifications</label><label><input id="set_email" type="checkbox" ${s.email_notifications?'checked':''}> Email notifications</label><button>ذخیره</button></form><hr><label>API URL<input value="${esc(API_BASE)}" readonly></label></div>`}
async function updateSettings(e){e.preventDefault();try{await put('/api/settings',{language:$('#set_language').value,theme:$('#set_theme').value,notifications_enabled:$('#set_notifications').checked?1:0,email_notifications:$('#set_email').checked?1:0});toast('تنظیمات ذخیره شول')}catch(x){toast(x.message)}}

/* ================= START ================= */
render();
</script>
</body>
</html>
